"""empty message

Revision ID: beb11a35dbfd
Revises: 
Create Date: 2023-01-17 14:03:36.909360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'beb11a35dbfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text_driver', postgresql.ENUM('SBER_GPT', name='charactertextdriver'), nullable=False),
    sa.Column('tts_driver', postgresql.ENUM('GOOGLE_TTS', name='characterttsdriver'), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__characters')),
    sa.UniqueConstraint('id', name=op.f('uq__characters__id'))
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'tg_id', 'username', name=op.f('pk__users')),
    sa.UniqueConstraint('id', name=op.f('uq__users__id')),
    sa.UniqueConstraint('tg_id', name=op.f('uq__users__tg_id')),
    sa.UniqueConstraint('username', name=op.f('uq__users__username'))
    )
    op.create_table('messages',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sender_type', postgresql.ENUM('USER', 'CHARACTER', name='sendertypes'), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('character_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk__messages__character_id__characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__messages__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__messages')),
    sa.UniqueConstraint('id', name=op.f('uq__messages__id')),
    sa.UniqueConstraint('user_id', 'character_id', name=op.f('uq__messages__user_id_character_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_table('characters')
    op.execute('drop type charactertextdriver')
    op.execute('drop type characterttsdriver')
    op.execute('drop type sendertypes')
    # ### end Alembic commands ###
