"""empty message

Revision ID: 67d5b84f9b6f
Revises: d6d73fc8d749
Create Date: 2023-01-18 09:50:06.766002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d5b84f9b6f'
down_revision = 'd6d73fc8d749'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix__messages__message'), 'messages', ['message'], unique=False)
    op.drop_constraint('uq__users__tg_id', 'users', type_='unique')
    op.create_index(op.f('ix__users__tg_id'), 'users', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__users__tg_id'), table_name='users')
    op.create_unique_constraint('uq__users__tg_id', 'users', ['tg_id'])
    op.drop_index(op.f('ix__messages__message'), table_name='messages')
    # ### end Alembic commands ###
