"""empty message

Revision ID: d6d73fc8d749
Revises: 37a627ab709b
Create Date: 2023-01-17 18:13:40.343434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6d73fc8d749'
down_revision = '37a627ab709b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_character_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk__users__active_character_id__characters'), 'users', 'characters', ['active_character_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__users__active_character_id__characters'), 'users', type_='foreignkey')
    op.drop_column('users', 'active_character_id')
    # ### end Alembic commands ###
