"""empty message

Revision ID: 37a627ab709b
Revises: 2fc6d90df54d
Create Date: 2023-01-17 14:08:33.682583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a627ab709b'
down_revision = '2fc6d90df54d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq__messages__user_id_character_id', 'messages', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq__messages__user_id_character_id', 'messages', ['user_id', 'character_id'])
    # ### end Alembic commands ###
